services:
  - type: web
    name: youtube-clipper
    env: node
    buildCommand: ./render-build.sh
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
